services:
  auth:
    build:
      dockerfile: ./Dockerfile
    image: libertai-api
    container_name: libertai-api
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - "8090:8000"
    env_file:
      - .env
    networks:
      - ip6net

networks:
  ip6net:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8::/64